name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Serup ASP .NET
      uses: nuget/setup-nuget@1
      with: 
        nuget-version: ${{env.NUGET_VERSION}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release -o /WebInterface/publish
    - name: Deploy
      uses: azure/webapps-deploy@2
      with:
        app-name: BrianStiner-Web-App
        publish-profile: ${{secrets.WEBAPP_PUBLISH_PROFILE}}
        package: /WebInterface/publish
